releases:
  - name: aws-broker
    version: v3

jobs:
  - name: rds_broker_z1
    instances: 1
    resource_pool: rds_broker_z1
    templates:
      - name: rds-broker
        release: aws-broker
    properties:
      rds-broker:
        aws_access_key_id: ""
        aws_secret_access_key: ""
        aws_region: "eu-west-1"
        password: (( grab secrets.rds_broker_admin_password ))
        catalog:
          services:
            - id: "ce71b484-d542-40f7-9dd4-5526e38c81ba"
              name: "rds"
              description: "AWS RDS PostgreSQL service"
              bindable: true
              tags:
                - "postgres"
                - "relational"
              metadata:
                displayName: "AWS RDS Postgres"
                imageUrl: ""
                longDescription: "AWS RDS postgres service"
                providerDisplayName: "Amazon Web Services"
                documentationUrl: "https://aws.amazon.com/documentation/rds/"
                supportUrl: "https://forums.aws.amazon.com/forum.jspa?forumID=60"
              plan_updateable: true
              plans:
                - id: "5b8282cf-a669-4ffc-b426-c169a7bbfc71"
                  name: "5.6-medium"
                  description: "RDS Postgres 9.4.5 (db.m3.medium, 10Gb)"
                  metadata:
                    costs:
                      - amount:
                          usd: 0.180
                        unit: "HOUR"
                    bullets:
                      - "Dedicated Postgres 9.4.5 server"
                      - "Postgres 9.4.5"
                      - "AWS RDS"
                  rds_properties:
                    db_instance_class: "db.m3.medium"
                    engine: "postgres"
                    engine_version: "9.4.5"
                    allocated_storage: 10
                    auto_minor_version_upgrade: true
                    multi_az: false
                    publicly_accessible: false
                    copy_tags_to_snapshot: true
                    skip_final_snapshot: false
                    db_subnet_group_name: ""
                    vpc_security_group_ids: []
                    db_security_groups: []

