meta:
  environment: (( grab terraform_outputs.environment ))

name: (( grab meta.environment ))
director_uuid: ~

releases:
  - name: cf
    version: 237
    url: https://bosh.io/d/github.com/cloudfoundry/cf-release?v=237
    sha1: 8996122278b03b6ba21ec673812d2075c37f1097
  - name: diego
    version: 0.1472.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/diego-release?v=0.1472.0
    sha1: a143e9e850ee794beb27bcd9ee9425406beb2987
  - name: garden-linux
    version: 0.337.0
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/garden-linux-release?v=0.337.0
    sha1: d1d81d56c3c07f6f9f04ebddc68e51b8a3cf541d
  - name: etcd
    version: 49
    url: https://bosh.io/d/github.com/cloudfoundry-incubator/etcd-release?v=49
    sha1: 5d145db1ddda984faf4777e022a748b355060478
  - name: cflinuxfs2-rootfs
    version: 1.5.0
    url: https://bosh.io/d/github.com/cloudfoundry/cflinuxfs2-rootfs-release?v=1.5.0
    sha1: 4ab6166d800668ad3e9c2c10cfd3403a7de5885f
  - name: paas-haproxy
    version: 0.0.4
  - name: routing
    version: commit-bfe3632ad6a2d143279db865aa050aea076fef9e

stemcells:
  - alias: default
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
    version: 3232.4

update:
  canaries: 0
  max_in_flight: 2
  canary_watch_time: 30000-600000
  update_watch_time: 5000-600000
  serial: false
