resource_pools:
  - name: rds_broker_z1
    network: cf1
    stemcell: (( grab meta.stemcell ))
    env: (( grab meta.default_env ))
    cloud_properties:
      instance_type: m3.medium
      ephemeral_disk:
        size: 10240
        type: gp2
      availability_zone: (( grab meta.zones.z1 ))
      iam_instance_profile: cf-cloudcontroller

jobs:
  - name: rds_broker_z1
    networks:
    - name: cf1
      static_ips: (( static_ips(15) ))
